### ISSUE TITLE
Dexcom Account ID

### ISSUE THREAD

**Issue by MatBat1117** [gagebenne/pydexcom#38] opened 2023-03-31 03:00 UTC
Hey you might remember an issue I raised before asking about micropython. I've decided on using circuitpython and it seems I've hit one final roadblock to make everything work. For some reason I cannot get adafruit_requests to get my account ID. I am stuck on the "Account ID null or empty" error and I was wondering if you either know of a way to manually get my dexcom ID so I could just make it a constant or if you could help me resolve the problem with adafruit requests somehow.

**Comment by elnjensen** [comment] 2023-03-31 11:57
Do you mean the `username` field in the code?   If so, it's the username you use to log in to Dexcom Clarity.  If you go to https://clarity.dexcom.com/ there's a "I forgot username or password" link that should let you recover it if you don't know what it is. 

Feel free to post example code here (obviously not with a password) if the issue is something different. 

Glad that you're close to getting this working with circuitpython!

**Comment by MatBat1117** [comment] 2023-03-31 12:16
So I am not able to get to my computer right now so I am writing this on my phone but I am referencing the account_id in the _init_.py file of this module. The reason I am wondering if there is some way for me to get this manually is because I cannot seem to get around the Account_ID EMPTY OR NULL error and I am certain it is some problem with adafruit_requests as I tries the code with regular requests and python and it worked was able to retrieve a glucose reading with no error.

**Comment by MatBat1117** [comment] 2023-03-31 12:16
So I am not able to get to my computer right now so I am writing this on my phone but I am referencing the account_id in your init file

**Comment by MatBat1117** [comment] 2023-03-31 12:22
So I am not able to get to my computer right now so I am writing this on my phone but I am referencing the account_id in the _init_.py file. I am running into the error ACOUNT ID NULL OR EMPTY and can't seem to get around it. I am pretty certain this is an issue with adafruit_requests (the circuit python requests) as I tried to get a glucose reading in just python with requests and it worked. I figured that if there were some way for me to find this account_id number and manually set it in the code I might be ok.

**Comment by elnjensen** [comment] 2023-03-31 13:18
The comment in the relevant part of the code says this:

"""
The Dexcom Share API at DEXCOM_AUTHENTICATE_ENDPOINT returns the account ID if credentials are valid -- whether the username is a classic username or email. Using the account ID the DEXCOM_LOGIN_ID_ENDPOINT is used to fetch a session ID.
"""

So it looks like you're failing authentication- possibly with wrong credentials, or possibly something is different about the `adafruit_requests` library. 

I'd triple-check your credentials first, but if that doesn't help, you could try to see if you can get the account ID at that  point in your desktop code. 

Ultimately it would be nice to get this working without workarounds.  I have a Raspberry Pi around somewhere that I could play with, but will likely take me a little while to find time for this.

**Comment by gagebenne** [comment] 2023-04-21 21:09
Thanks @elnjensen. I'm at PyCon at the CircuitPython open space. I wasn't too familiar with CircuitPython / uPython, but feeling a bit more comfortable with the process of getting things in the community bundle for CircuitPython. I think forking (and potentially) adding to the CircuitPython community library bundle is the way to go. I'd like these embedded-style `pydexcom`s to stay still under my name, admitting that I then acquire the maintenance burden as well.

**Comment by gagebenne** [comment] 2023-04-21 21:10
I'm going to close this with the idea in mind that I expect to see a `pydexcom` CircuitPython-compatible library prior to the end of PyCon 2023.

**Closed by gagebenne** 2023-04-21 21:10 UTC
